services:
  - type: web
    name: portfolio-backend
    env: docker
    dockerfilePath: ./Dockerfile
    branch: main
    healthCheckPath: /api/projects # More specific health check
    envVars:
      - key: APP_KEY
        generateValue: true
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: sqlite
      - key: CORS_ALLOWED_ORIGINS
        value: https://portfolio-frontend.onrender.com # Ensure CORS is properly configured

  - type: web
    name: portfolio-frontend
    env: static
    buildCommand: cd portfolio-frontend && npm install && npm run build
    staticPublishPath: ./portfolio-frontend/dist
    branch: main
    envVars:
      - key: VITE_API_URL
        value: https://portfolio-backend.onrender.com/api
